name: docs

on:
  push:
    branches: [main]  # для latest версии
  release:
    types: [published]  # для stable версии

jobs:
  deploy-stable:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install sphinx furo

    - name: Generate API docs
      run: |
        cd docs
        chmod +x genapidoc.sh
        ./genapidoc.sh

    - name: Build and deploy stable docs
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs
        publish_path: ./
      env:
        NADZORING_DOCS_TYPE: stable

  deploy-latest:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install sphinx furo

    - name: Generate API docs
      run: |
        cd docs
        chmod +x genapidoc.sh
        ./genapidoc.sh

    - name: Build and deploy latest docs
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs
        publish_path: ./latest
      env:
        NADZORING_DOCS_TYPE: latest
